### Description:
### --------------------------------
### This file holds the configuration to start the browser 
### and perform concolic execution analysis.

WORKSPACE: "/home/jackfromeast/Desktop/TheHulk/tmp/concolic"

chrome:
  CHROME_EXECUTABLE_PATH: "/usr/bin/google-chrome"
  CHROME_FLAGS: [
    # "--enable-blink-features=RecordDOMClobberingSitesAny,RecordDOMAccessAPIAny",
    # "-js-flags=--trace-document-lookup",
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
    # --disable-http2
  ]
  HEADLESS: false
  DEVTOOLS: true

collector:
  # Collectors configuration
  COLLECT_AND_CREATE_PAGE: false
  COLLECT_CONSOLE_LOGS: false
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: false
  COLLECT_CSS: false
  COLLECT_SCRIPTS: false
  COLLECT_BROWSER_STDERR: false
  COLLECT_BROWSER_STDOUT: false
  COLLECT_XHR_REQUESTS: false
  COLLECT_FETCH_REQUESTS: false
  EXTRACT_DOM_LOOKUPS: false


navigator:
  BROWSER: "chrome"
  WAIT_BEFORE_NEXT_URL: 1000
  INITIAL_URL: "http://10.161.159.131:8001/array/array-values-1.html"
  NAVIGATION_TIMEOUT: 0
  # For puppeteer, options:
  # ['load', 'domcontentloaded']
  # ['networkidle0']
  # For playwright:
  # load|domcontentloaded|networkidle|commit
  NAVIGATION_WAIT_UNTIL: 'domcontentloaded'


proxy:
  PROXY_SERVER: "localhost"
  PROXY_PORT: 8899

callbacks:
  BEFORE_LOAD_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/browser/callbacks/install-runtime-analysis-callbacks-playwright.js"
      function_name: "installJalangi2AndAnalysisCb"
  
  PAGE_ACTIONS_CBS:
    - file: "./callbacks/wait-forever-callbacks.js"
      function_name: "manuallyInteractForeverCb"

  AFTER_LOAD_CBS: []

  POST_VISIT_CBS: []

others:
  ### To switch to another analysis, also need to change the entry.js file in the runtime analysis
  ANALYSIS_NAME: "TaintTracking"
  ANALYSIS_SCRIPT_PATH: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/runtime-analysis/dist/thehulk-runtime-analysis.bundle.js"
  JALANGI2_RUNTIME_PATH: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/runtime-jalangi2/dist/thehulk-jalangi2-runtime.bundle.js"
