scheduler:
  TEST_NAME: "verify-contenteditable-top-5k"
  # Path to workspace (base directory for storing results)
  WORKSPACE: "/home/xxxxxxxxxxxx/Desktop/TheHulk/output/"

  # Option: "seed" or "list"
  MODE: "seed"
  SEED_URL: "https://admin.shopify.com/store/was0d1?from=accountSettings"
  URL_LIST: "/home/xxxxxxxxxxxx/Desktop/TheHulk/html-injection/probe-contenteditable/dataset/top-5k-urls-contenteditable-elements.csv"
  URL_LIST_FROM: 1
  URL_LIST_TO: -1      # -1 for all urls

  # Format of the urls.csv file:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  # Maximum number of workers to run in parallel
  MAX_WORKER: 32
  # Maximum number of urls to visit
  MAX_URL: 1
  # Time budget for each worker to visit a single url
  TIMEOUT_PER_DOMAIN: 1800000


