scheduler:
  TEST_NAME: "FOXHOUND-DOM-TAINTFLOWS-ROUND1-TOP500"
  # Path to workspace (base directory for storing results)
  WORKSPACE: "/home/xxxxxxxxxxxx/Desktop/TheHulk/output/"

  # Option: "seed" or "list"
  MODE: "list"
  SEED_URL: "https://google.com"
  URL_LIST: "/home/xxxxxxxxxxxx/Desktop/TheHulk/jaw-v3-thething/input/tranco_Z2QWG_unique.csv"
  URL_LIST_FROM: 0
  URL_LIST_TO: 500

  # Format of the urls.csv file:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  # Maximum number of workers to run in parallel
  MAX_WORKER: 16
  # Maximum number of urls to visit
  MAX_URL: 20
  # Time budget for each worker to visit a single domain
  TIMEOUT_PER_DOMAIN: 5400000


