scheduler:
  # Path to workspace (base directory for storing results)
  WORKSPACE: "/home/jackfromeast/Desktop/TheHulk/tmp/test-webpage"

  # Option: "seed" or "list"
  MODE: "list"
  SEED_URL: "https://www.google.com"
  URL_LIST: "/home/jackfromeast/Desktop/TheHulk/tmp/urls.csv"

  # Format of the urls.csv file:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  # Maximum number of workers to run in parallel
  MAX_WORKER: 1
  # Maximum number of urls to visit
  MAX_URL: 1
  # Time budget for each worker to visit a single url
  TIMEOUT_PER_URL: 1800000


