chrome:
  CHROME_EXECUTABLE_PATH: "/home/jackfromeast/Desktop/SafeLookup/tools/Chromes/chrome-clobber/src/out/x64.debug.clobber/chrome"
  CHROME_FLAGS: [
    "--enable-blink-features=RecordDOMClobberingSitesAny,RecordDOMAccessAPIAny",
    "-js-flags=--trace-document-lookup",
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false

collector:
  # Collectors configuration
  COLLECT_AND_CREATE_PAGE: true
  COLLECT_CONSOLE_LOGS: true
  COLLECT_REQUESTS: true
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: true
  COLLECT_CSS: true
  COLLECT_SCRIPTS: true
  COLLECT_BROWSER_STDERR: true
  COLLECT_BROWSER_STDOUT: true
  COLLECT_XHR_REQUESTS: true
  COLLECT_FETCH_REQUESTS: true
  EXTRACT_DOM_LOOKUPS: true


navigator:
  WAIT_BEFORE_NEXT_URL: 1000


callbacks:
  BEFORE_LOAD_CBS:
    - file: "./callbacks/disable-csp-callbacks.js"
      function_name: "disableCSPCb"
      
    - file: "./callbacks/forbid-url-loading-callbacks.js"
      function_name: "forbidURLNavigationCb"
  
  PAGE_ACTIONS_CBS:
    - file: "./callbacks/manually-actions-callbacks.js"
      function_name: "manuallyInteractCb"

  AFTER_LOAD_CBS:
    - file: "./callbacks/extract-clobberable-callbacks.js"
      function_name: "extractDOMCLookupsCb"

  POST_VISIT_CBS:
    - file: "./callbacks/compile-ql-query-callbacks.js"
      function_name: "compileQLQueryCb"
    
    - file: "./callbacks/create-ql-db-callbacks.js"
      function_name: "createCodeQLDatabaseCb"

others:
  CODEQL_QUERY_SAVE_PATH: "/home/jackfromeast/Desktop/TheHulk/codeql-query/WebsiteSpecific"