scheduler:
  workspace: "/home/jackfromeast/Desktop/TheHulk/tmp/test-webpage"               # Path to workspace (base directory for storing results)

  crawlerMode: "seed"                        # Option: "seed" or "list"
  seedURL: "https://www.google.com"          # Seed URL
  urlList: "path/to/urls.csv"                # Path to URL list

  # urllist.csv format:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  maxWorkers: 1
  maxUrl: 1
  timeOutPerUrl: 1800000


