chrome:
  CHROME_EXECUTABLE_PATH: "/home/jackfromeast/Desktop/SafeLookup/tools/Chromes/chrome-clobber/src/out/x64.debug.clobber/chrome"
  CHROME_FLAGS: [
    "--enable-blink-features=RecordDOMClobberingSitesAny,RecordDOMAccessAPIAny",
    "-js-flags=--trace-document-lookup",
    "--disable-blink-features=AutomationControlled",
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false
  DEVTOOLS: false

collector:
  # Collectors configuration
  COLLECT_AND_CREATE_PAGE: true
  COLLECT_CONSOLE_LOGS: false
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: true
  COLLECT_CSS: true
  COLLECT_SCRIPTS: true
  COLLECT_BROWSER_STDERR: true
  COLLECT_BROWSER_STDOUT: true
  COLLECT_XHR_REQUESTS: true
  COLLECT_FETCH_REQUESTS: true
  EXTRACT_DOM_LOOKUPS: true
  COLLECT_ALT_URLS: false


navigator:
  WAIT_BEFORE_NEXT_URL: 1000
  # Used during page.goto(url, {waitUnitl: NAVIGATION_WAIT_UNTIL})
  # Options:
  # ['load', 'domcontentloaded']
  # ['networkidle0']
  NAVIGATION_WAIT_UNTIL: ['networkidle2']
  NAVIGATION_TIMEOUT: 0


callbacks:
  BEFORE_LOAD_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/disable-csp-callbacks.js"
      function_name: "disableCSPCb"
      
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/forbid-url-loading-callbacks.js"
      function_name: "forbidURLNavigationCb"
  
  PAGE_ACTIONS_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/wait-forever-callbacks.js"
      function_name: "manuallyInteractForeverCb"

  AFTER_LOAD_CBS: []

  POST_VISIT_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/extract-clobberable-callbacks.js"
      function_name: "extractDOMCLookupsCb"
      
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/compile-ql-query-callbacks.js"
      function_name: "compileQLQueryCb"
    
    - file: "/home/jackfromeast/Desktop/TheHulk/crawler/src/callbacks/create-ql-db-callbacks.js"
      function_name: "createCodeQLDatabaseCb"

others:
  CODEQL_QUERY_SAVE_PATH: "/home/jackfromeast/Desktop/TheHulk/codeql-query/WebsiteSpecific"
  COLLECT_DOM_LOOKUP_HINTS: "Collect Start." # or ''
