scheduler:
  TEST_NAME: "canvas"
  # Path to workspace (base directory for storing results)
  WORKSPACE: "/home/jackfromeast/Desktop/TheHulk/output/canvas-jhu/"

  # Option: "seed" or "list"
  MODE: "seed"
  SEED_URL: "https://jhu.instructure.com/courses/49399/announcements"
  URL_LIST: "/home/jackfromeast/Desktop/TheHulk/tmp/urls.csv"
  URL_LIST_FROM: 0
  URL_LIST_TO: 1

  # Format of the urls.csv file:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  # Maximum number of workers to run in parallel
  MAX_WORKER: 1
  # Maximum number of urls to visit
  MAX_URL: 1
  # Time budget for each worker to visit a single domain
  TIMEOUT_PER_DOMAIN: 1800000


