scheduler:
  TEST_NAME: "AE-E3-1"
  # Path to workspace (base directory for storing results)
  WORKSPACE: "tasks/ae-run-gadget-detection-e3-1/output"

  # Option: "seed" or "list"
  MODE: "list"
  SEED_URL: "https://upi.com"
  URL_LIST: "tasks/ae-run-gadget-detection-e3-1/input/vulnerable-domains-Tranco-Top-5K.csv"
  FILTERED_URL_LIST: ""
  URL_LIST_FROM: 0
  URL_LIST_TO: -1

  # Format of the urls.csv file:
  #   1,google.com
  #   2,facebook.com
  #   3,amazonaws.com
  #   4,microsoft.com
  #   5,apple.com
  #   6,googleapis.com
  #   7,akamaiedge.net
  #   8,youtube.com
  #   9,a-msedge.net
  #   10,twitter.com  

  # Maximum number of workers to run in parallel
  MAX_WORKER: 4
  # Maximum number of urls to visit
  MAX_URL: 1
  # Time budget for each worker to visit a single domain
  TIMEOUT_PER_DOMAIN: 300000


