### Description:
### --------------------------------
### This file holds the configuration to start the browser 
### and perform concolic execution analysis.

chrome:
  CHROME_EXECUTABLE_PATH: "/usr/bin/google-chrome"
  CHROME_FLAGS: [
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false
  DEVTOOLS: false

foxhound:
  FOXHOUND_EXECUTABLE_PATH: "/home/jackfromeast/Desktop/TheHulk/jaw-v3-thething/crawler/foxhound/project-foxhound/obj-tf-release/dist/foxhound/foxhound"
  FOXHOUND_FLAGS: [
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false
  DEVTOOLS: false


collector:
  # Collectors configuration
  COLLECT_ALT_URLS: true
  COLLECT_AND_CREATE_PAGE: true
  COLLECT_CONSOLE_LOGS: true
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: false
  COLLECT_CSS: false
  COLLECT_SCRIPTS: false
  COLLECT_BROWSER_STDERR: false
  COLLECT_BROWSER_STDOUT: false
  COLLECT_XHR_REQUESTS: false
  COLLECT_FETCH_REQUESTS: false
  EXTRACT_DOM_LOOKUPS: false
  COLLECT_TAINTING_FLOWS: true

navigator:
  BROWSER: "chrome"
  WAIT_BEFORE_NEXT_URL: 5000
  NAVIGATION_TIMEOUT: 0
  # For puppeteer, options:
  # ['load', 'domcontentloaded']
  # ['networkidle0']
  # For playwright:
  # load|domcontentloaded|networkidle|commit
  NAVIGATION_WAIT_UNTIL: 'domcontentloaded'

proxy:
  PROXY_SERVER: "localhost"
  PROXY_PORT: 8877

callbacks:
  BEFORE_LOAD_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/browser/callbacks/install-runtime-analysis-callbacks-playwright.js"
      function_name: "installJalangi2AndAnalysisCb"

    - file: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/defined-tasks/run-taint-tracking-trenco/callbacks/collect-taint-flow-callbacks.js"
      function_name: "collectTaintflowsAtRuntimeCb"

  PAGE_ACTIONS_CBS:
    - file: /home/jackfromeast/Desktop/TheHulk/concolic-engine/defined-tasks/run-taint-tracking-builtins/callbacks/wait-for-five-sec-callbacks.js
      function_name: "waitForFiveSecCb"

    - file: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/defined-tasks/run-taint-tracking-trenco/callbacks/collect-clobberable-sources-sinks-callback.js"
      function_name: "collectSourcesSinksPerPageCallbacks"

  AFTER_LOAD_CBS:
    - file: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/defined-tasks/run-taint-tracking-builtins/callbacks/retest-if-jalangi2-not-found.js"
      function_name: "retestIfJalangi2NotFound"

  POST_VISIT_CBS: []
  
others:
  ### To switch to another analysis, also need to change the entry.js file in the runtime analysis
  ANALYSIS_NAME: "TaintTracking"
  ANALYSIS_SCRIPT_PATH: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/runtime-analysis/dist/thehulk-runtime-analysis.bundle.js"
  JALANGI2_RUNTIME_PATH: "/home/jackfromeast/Desktop/TheHulk/concolic-engine/runtime-jalangi2/dist/thehulk-jalangi2-runtime.bundle.js"
