### Description:
### --------------------------------
### This file holds the configuration to start the browser 
### and perform concolic execution analysis.

chrome:
  CHROME_EXECUTABLE_PATH: "/usr/bin/google-chrome"
  CHROME_FLAGS: [
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: true
  DEVTOOLS: false

foxhound:
  FOXHOUND_EXECUTABLE_PATH: "/home/jackfromeast/Desktop/TheHulk/jaw-v3-thething/crawler/foxhound/project-foxhound/obj-tf-release/dist/foxhound/foxhound"
  FOXHOUND_FLAGS: [
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: true
  DEVTOOLS: false


collector:
  # Collectors configuration
  COLLECT_ALT_URLS: true
  COLLECT_AND_CREATE_PAGE: true
  COLLECT_CONSOLE_LOGS: true
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: false
  COLLECT_CSS: false
  COLLECT_SCRIPTS: false
  COLLECT_BROWSER_STDERR: false
  COLLECT_BROWSER_STDOUT: false
  COLLECT_XHR_REQUESTS: false
  COLLECT_FETCH_REQUESTS: false
  EXTRACT_DOM_LOOKUPS: false
  COLLECT_TAINTING_FLOWS: false

navigator:
  BROWSER: "chrome"
  WAIT_BEFORE_NEXT_URL: 1000
  NAVIGATION_TIMEOUT: 0
  # For puppeteer, options:
  # ['load', 'domcontentloaded']
  # ['networkidle0']
  # For playwright:
  # load|domcontentloaded|networkidle|commit
  NAVIGATION_WAIT_UNTIL: 'domcontentloaded'

proxy:
  PROXY_SERVER: "localhost"
  PROXY_PORT: 8899

callbacks:
  BEFORE_LOAD_CBS:
    - file: "gadget-detection/browser/callbacks/install-runtime-analysis-callbacks-playwright.js"
      function_name: "installJalangi2AndAnalysisCb"
  
  PAGE_ACTIONS_CBS:
      - file: tasks/run-taint-tracking-dom-clobbering-collection/callbacks/wait-for-five-sec-callbacks.js
        function_name: "waitForFiveSecCb"

      - file: "tasks/run-taint-tracking-dom-clobbering-collection/callbacks/collect-results-callback.js"
        function_name: "collectResultPerPageCallbacks"

      - file: "tasks/run-taint-tracking-dom-clobbering-collection/callbacks/exploit-generator-callbacks.js"
        function_name: "generateExploitCallbacks"

  AFTER_LOAD_CBS:
    - file: "tasks/run-taint-tracking-dom-clobbering-collection/callbacks/retest-if-jalangi2-not-found.js"
      function_name: "retestIfJalangi2NotFound"
  
  POST_VISIT_CBS: 
    - file: "tasks/run-taint-tracking-dom-clobbering-collection/callbacks/collect-results-all-callbacks.js"
      function_name: "collectResultsPerTaskCallbacks"
  
  POST_PROCESS_CBS:
    PER_PAGE: []
    AFTER_ALL_DOMAINS: []

others:
  ### To switch to another analysis, also need to change the entry.js file in the runtime analysis
  ANALYSIS_NAME: "TaintTracking"
  ANALYSIS_SCRIPT_PATH: "gadget-detection/runtime-analysis/dist/thehulk-runtime-analysis.bundle.js"
  JALANGI2_RUNTIME_PATH: "gadget-detection/runtime-jalangi2/dist/thehulk-jalangi2-runtime.bundle.js"