### Description:
### --------------------------------
### This file holds the configuration to start the browser 
### and perform concolic execution analysis.

chrome:
  CHROME_EXECUTABLE_PATH: "/home/xxxxxxxxxxxx/Desktop/SafeLookup/tools/Chromes/chrome-clobber/src/out/x64.debug.clobber/chrome"
  CHROME_FLAGS: [
    "--enable-blink-features=RecordDOMClobberingSitesAny",
    "-js-flags=--trace-document-lookup",
    "--disable-blink-features=AutomationControlled",
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: true
  DEVTOOLS: false

foxhound:
  FOXHOUND_EXECUTABLE_PATH: "/home/xxxxxxxxxxxx/Desktop/TheHulk/jaw-v3-thething/crawler/foxhound/project-foxhound/obj-tf-release/dist/foxhound/foxhound"
  FOXHOUND_FLAGS: [
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false
  DEVTOOLS: false


collector:
  # Collectors configuration
  COLLECT_ALT_URLS: true
  COLLECT_AND_CREATE_PAGE: true
  COLLECT_CONSOLE_LOGS: true
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: false
  COLLECT_CSS: false
  COLLECT_SCRIPTS: false
  COLLECT_BROWSER_STDERR: false
  COLLECT_BROWSER_STDOUT: false
  COLLECT_XHR_REQUESTS: false
  COLLECT_FETCH_REQUESTS: false
  EXTRACT_DOM_LOOKUPS: true
  COLLECT_TAINTING_FLOWS: false

navigator:
  BROWSER: "chrome"
  WAIT_BEFORE_NEXT_URL: 1000
  NAVIGATION_TIMEOUT: 0
  # For puppeteer, options:
  # ['load', 'domcontentloaded']
  # ['networkidle0']
  # For playwright:
  # load|domcontentloaded|networkidle|commit
  NAVIGATION_WAIT_UNTIL: 'domcontentloaded'

proxy:
  PROXY_SERVER: false
  PROXY_PORT: false

callbacks:
  BEFORE_LOAD_CBS: []
  
  PAGE_ACTIONS_CBS:
      - file: /home/xxxxxxxxxxxx/Desktop/TheHulk/concolic-engine/defined-tasks/run-taint-tracking-builtins/callbacks/wait-for-five-sec-callbacks.js
        function_name: "waitForFiveSecCb"

  AFTER_LOAD_CBS: 
    - file: "/home/xxxxxxxxxxxx/Desktop/TheHulk/crawler/src/callbacks/extract-clobberable-callbacks.js"
      function_name: "extractDOMCLookupsCb"

  POST_VISIT_CBS: []

others:
  ### To switch to another analysis, also need to change the entry.js file in the runtime analysis
  ANALYSIS_NAME: "Jalangi2Only"
  # ANALYSIS_SCRIPT_PATH: "/home/xxxxxxxxxxxx/Desktop/TheHulk/concolic-engine/runtime-analysis/dist/thehulk-runtime-analysis.bundle.js"
  JALANGI2_RUNTIME_PATH: "/home/xxxxxxxxxxxx/Desktop/TheHulk/concolic-engine/runtime-jalangi2/dist/thehulk-jalangi2-runtime.bundle.js"