### Description:
### --------------------------------
### This file holds the configuration to start the browser 
### and perform concolic execution analysis.

WORKSPACE: "/home/jackfromeast/Desktop/TheHulk/tmp/concolic"

chrome:
  CHROME_EXECUTABLE_PATH: "/usr/bin/google-chrome"
  CHROME_FLAGS: [
    # "--enable-blink-features=RecordDOMClobberingSitesAny,RecordDOMAccessAPIAny",
    # "-js-flags=--trace-document-lookup",
    "--no-sandbox",
    '--disable-setuid-sandbox',
    '--disable-gpu'
  ]
  HEADLESS: false

collector:
  # Collectors configuration
  COLLECT_AND_CREATE_PAGE: false
  COLLECT_CONSOLE_LOGS: false
  COLLECT_REQUESTS: false
  COLLECT_WEB_STORAGE: false
  COLLECT_COOKIES: false
  COLLECT_HTML: false
  COLLECT_CSS: false
  COLLECT_SCRIPTS: false
  COLLECT_BROWSER_STDERR: false
  COLLECT_BROWSER_STDOUT: false
  COLLECT_XHR_REQUESTS: false
  COLLECT_FETCH_REQUESTS: false
  EXTRACT_DOM_LOOKUPS: false


navigator:
  WAIT_BEFORE_NEXT_URL: 1000
  INITIAL_URL: "about:blank"

proxy:
  PROXY_SERVER: "localhost"
  PROXY_PORT: 8899

callbacks:
  BEFORE_LOAD_CBS:
    - file: "./callbacks/disable-csp-callbacks.js"
      function_name: "disableCSPCb"

    - file: "./callbacks/forbid-url-loading-callbacks.js"
      function_name: "forbidURLNavigationCb"
  
  PAGE_ACTIONS_CBS:
    - file: "./callbacks/manually-actions-callbacks.js"
      function_name: "manuallyInteractCb"

  AFTER_LOAD_CBS: []

  POST_VISIT_CBS: []